### ISSUE TITLE
using ffmpeg instead of imagemagick

### ISSUE THREAD

**Issue by imr0** [cjbassi/swaylock-blur#1]
Hi,

I am experimenting with a similar script as well, and found that for me doing a Gaussian blur on the screenshot with ffmpeg instead of imagemagick is significantly faster.

My not-so-sophisticated script that highlights my point:
grim -t jpeg /tmp/screenshot.jpg && ffmpeg -loglevel panic -y -i /tmp/screenshot.jpg -vf "gblur=sigma=50" /tmp/blur.jpg && swaylock -i /tmp/blur.jpg

Maybe it's worth considering using this.

**Comment by cjbassi** [comment]
Thanks! I noticed it was a lot faster for me too so I just switched over. I also added a `--blur-sigma` flag to control the blur since that was easy to add with ffmpeg now.
