### ISSUE TITLE
Not able to pass option '-K' to swaylock

### ISSUE THREAD

**Issue by cinocode** [cjbassi/swaylock-blur#3]
Hi, I want to hide my keyboard layout from swaylock-blur and tried to do that with "swaylock-blur -K".
Running "swaylock -K" hides the layout. From your help text " swaylock-blur [OPTIONS] [swaylock_args]..." I assumed I could just put the option at the end and it gets passed through.

Instead I get:
error: Found argument '-K' which wasn't expected, or isn't valid in this context.

I'm on:
local/sway 1.1.1-1
    Tiling Wayland compositor and replacement for the i3 window manager
local/swaylock 1.4-1
    Screen locker for Wayland
local/swaylock-blur-bin 0.3.0-1
    A small Rust program that runs swaylock and sets the image to a blurred screenshot of the desktop

**Comment by cjbassi** [comment]
You have to do `swaylock-blur -- -K` to pass it to swaylock itself. I should probably update the help menu since it is confusing.

**Comment by cjbassi** [comment]
I added a comment to the arguments, but I wasn't able to edit the content inline because I'm using structopt, although I think it's probably good enough.

**Comment by cinocode** [comment]
Works like a charm. Thanks for the clarification.
